import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { login } from './authAPI';

const token = localStorage.getItem('token');

const initialState = {
  isAuthenticated: !!token,
  token: token,
  status: 'idle',
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const loginAsync = createAsyncThunk(
  'auth/login',
  async ({username, password}) => {
    const {data} = await login({username, password});

    // The value we return becomes the `fulfilled` action payload
    return data.data;
  }
);

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loginAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(loginAsync.fulfilled, (state, action) => {
        const data = action.payload;

        localStorage.setItem('token', data.token)

        state.status = 'idle';
        state.isAuthenticated = true;
        state.token = data.token;
      });
  },
});


export default authSlice.reducer;
